name: Build and Deploy React App

on:
  push:
    branches:
      - main  # change to your default branch if not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # or whatever your project uses

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React app
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/build
          server-dir: public_html/  # adjust this to your actual remote path
